spring.application.name=demo

#para definir el puerto
server.port=80

#para definir el formato de despliegue de fecha y hora
logging.pattern.dateformat=hh:mm

#para eliminar mensajes masivos de sprint
spring.main.banner-mode=off

#borrar cache
spring.thymeleaf.cache=false

spring.datasource.url=jdbc://localhost:3306/techshop

spring.datasource.username=root
spring.datasource.password=Mina1406

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.type.descriptor.sql.BasicBinder=TRACE

#informacion que utiliza para obtener acceso a storage
firebase.bucket.name=techshop-3475c.firebasestorage.app
firebase.storage.path=techshop
firebase.json.path=firebase
firebase.json.file=techshop-3475c-firebase-adminsdk-fbsvc-a32421ee70.json